<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Автозапуск</title>
</head>
<body>
    <h1>Добро пожаловать! Это мой кастомный код</h1>
    <script>
        alert("Код выполнен успешно!");
    </script>
</body>
</html>
